name: automerge
on:
  pull_request:
    types:
      - opened

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
      contents : write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN : "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FILTER_AUTHOR : "github-actions[bot]"
          MERGE_LABELS : "automated"
          MERGE_METHOD : "merge"
